### PR TITLE
Detailed instructions for class extension

### PR DESCRIPTION
**Pull request by LTLA**
This is very much a work in progress, just adding it as a PR to put it on the radar and to get feedback.

### CODE REVIEW

**Comment by LTLA** [comment]
There are probably a few aspects of the derivation that can be simplified, if one is willing to modify the manner in which _SummarizedExperiment_ does its subsetting/combining. In particular, something like `parallelSlotNames` would mean that users only need to re-define that method, and the base functions would take care of the subsetting and combining for all custom slots.

For example, a `parallelSlotNamesByRow` method might be used like this in `rbind`:

```r
setMethod("rbind", "SummarizedExperiment", function(..., deparse.level=1) {
    args <- list(...)
    ref <- args[[1]]
    all.row.slots <- parallelSlotNamesByRow(ref)
    
    row.combined <- vector("list", length(all.row.slots))
    names(row.combined) <- all.row.slots
    for (element in all.row.slots) {
        all.of.this <- lapply(args, slot, name=element)
        row.combined[[element]] <- do.call(c, all.of.this)
    }
    
    # turn off validity here...
    out <- callNextMethod()

    do.call(BiocGenerics:::replaceSlot, c(list(out), row.combined))
})
```

Obviously some work would be required to handle cases where the custom slots are 2D and the rows (or columns) are parallel to the rows of the `SummarizedExperiment`. One could imagine that `parallelSlotNamesByRow` returns a `DataFrame` containing the slot names as the row names; a list of combining functions as one field; a list of subsetting functions as another field; and a list of identity-checking functions as another field (e.g., to perform checks for equality when combining by column).

This capability would make life much easier for developers creating derived the class, as we would only need to modify `parallelSlotNamesByRow` and not need to write any of the boilerplate stuff.

**Comment by LTLA** [comment]
Thanks Martin, I made some modifications in line with your suggestions. Some extra thoughts:

- _testthat_ is a good idea but the SE package uses _RUnit_ and I don't have any experience with that.
- I didn't think `@rdname` would provide enough flexibility for documenting the class and its methods in a single *.Rd file, e.g., the current `SummarizedExperiment-class.Rd` documentation seems very customized and difficult to generate with Roxygen. Having said that, I've never tried.
- Not sure what the no-structure dispatch is meant to do. Seems like it wouldn't involve much extra work from the developer's side if they don't have to wrestle with the extra slots.

**Comment by mtmorgan** [comment]
Thanks @LTLA . Any class extension would be implemented in a new package so would be free to adopt whatever unit test framework is appropriate; testthat seems to be the current favorite so it seems that it should be used to illustrate here (even if that means both RUnit and testthat end up in SummarizedExperiment's Suggests: field).

The @rdname suggestion was just an attempt to tackle the use of roxygen2, and the challenge of documenting S4 objects and their methods. Another approach is to write a roxygen chunk at the top of the file that documents everything; maybe this partly undermines how roxygen2 encourages placing documentation in proximity to relevant code. Regardless, it seems valuable to capture the 'best practices' for documenting S4 objects and their methods.

One wants to introduce new classes in a conservative manner, and to make them as simple as possible (SingleCellExperiment is flirting with a complex and idiosyncratic design). Maybe there are data types that  fit well in the SummarizedExperiment context but have additional constraints or unique methods (all assays are non-negative matrices, there must be three of them, subsetting makes no sense, `foo()` is relevant on the derived but not SummarizedExperiment class...), and a simple class extension is the minimum change required to get there.

**Comment by LTLA** [comment]
- Added a testthat section demonstrating how to perform basic unit tests. 
- Added a section on documentation. Currently I'm suggesting people to split up their docs into one file for the constructor and another for the methods, to avoid an overly complicated `\usage`.

Still need to fit the simple case in somewhere.

**Comment by LTLA** [comment]
1. See Martin's comment above.
2. I did think about that, but I didn't bother as I didn't think it really mattered. If a developer can't figure out what `rowToRowMat` means, I would say that they've got bigger problems.

**Comment by LTLA** [comment]
@mtmorgan I remember you (or maybe Herve?) telling me to use the getters rather than `@`. I followed that advice, but I've forgotten the reasoning behind it. Is it just to protect against internal changes to the slot names? I mean, if I change the slot names, I'd probably have a lot of changes to make anyway, e.g., in my `BiocGenerics:::replaceSlots` calls.

**Comment by mtmorgan** [comment]
Yes avoiding use of slot names protects from changes in data representation. But more generally and, perhaps more important, it allows an interface that is helpful to users and an implementation that is convenient for developers. The trivial example is `IRanges()` which does _not_ have `start`, `end` and `width` slots! As a user I don't care which slots it implements; as a developer some combination will be more efficient than others. A second example is the lowly `DNAStringSet()`, which has nothing that I as a casual user recognize as a character vector.

**Comment by LTLA** [comment]
Sure, I understand why we need them for the user-side interface. But why do we need to use the getters internally as well, i.e., from the developer side? For example, the `ExampleClass` validity method uses the getters internally, but I don't see the advantage over just accessing the slots in these cases.

**Comment by mtmorgan** [comment]
The arguments will be basically the same, after an initial period of developing the class you'll be a user, even inside your package. And consistency helps both the developer and the colleague wondering what you're doing.

**Comment by hpages** [comment]
Yeah IRanges, DNAStringSet, CompressedList, DelayedArray etc... are WYSAGINWI (pronounced "wee-za-gin-wee") i.e. What You See And Get Is Not What's Inside ;-)

**Comment by hpages** [comment]
@LTLA I hate to implement the `[` and `c` methods too. That's why I worked hard on simplifying the process by introducing the `extractROWS` and more recently the `concatenateObjects` generics. `extractROWS` is for linear subsetting along the first dimension of an object. A Vector derivative should only need to implement an `extractROWS` method to have `x[i]` work out-of-the-box. In the case of a SummarizedExperiment object, since it's a vector derivative with the length going along its 1st dimension, `rbind()` is semantically equivalent to `c()`. I don't know if SummarizedExperiment supports `c` right now but it should. Then `rbind()` should just call that. There are probably many aspects of the current implementation of the `[` and `rbind` methods for SummarizedExperiment objects that could be revisited and simplified. I'm not sure about your `parallelSlotNamesByRow` proposal, I would need to take a closer look at it. It might be redundant with some low-level internal things that we have in S4Vectors. There is also the DataTable abstraction defined in S4Vectors that should play a role here.

**Comment by LTLA** [comment]
Yes, I recall discussing the `extractROWS` method with you, I think during the submission of _InteractionSet_. However, looking at the method in _SummarizedExperiment_, I just see:

```r
setMethod("extractROWS", "SummarizedExperiment",
    function(x, i)
    {
        i <- normalizeSingleBracketSubscript(i, x)
        x[i, ]
    }
)
```

... and I presume I still have to write a method for the derived class that handles the custom slots. The hope would be to have something like `parallelSlotNames` for `Vector` derivatives, which would handle it all automagically for me (see caveats above). I remember doing something like this for `GInteractions` in _InteractionSet_, and it was fantastically easy - add the slot names and it was done.

**Comment by hpages** [comment]
Yeah that's good example of something that needs to be revisited. I agree that derived classes that only add slots that are meant to be parallel to the object (i.e. parallel to its 1st dimension) shouldn't need to do anything except registering those slots via a `parallelSlotNames` method. The original implementation of SummarizedExperiment predates the introduction of `extractROWS` and `concatenateObjects` so doesn't take advantage of them. After I introduced `extractROWS` and `concatenateObjects` I refactored several Vector derivatives (e.g. Hits, Rle, IRanges, GRanges, GAlignments, etc...) to take advantage of them which led to a lot of simplifications. But I didn't refactored anything for SummarizedExperiment. A proper refactoring still needs to be done for this class. Then derived SummarizedExperiment classes that register the parallel slots via a `parallelSlotNames` method should get `x[i]`, `x[i,j]`, `c(x, y)` and `rbind(x, y)` for free. I think it's a just question of refactoring the current implementation of the `extractROWS`, `[`, and `rbind` methods for SummarizedExperiment objects. I don't think we need to introduce `parallelSlotNamesByRow` for that. That's what `parallelSlotNames` is for.

**Comment by LTLA** [comment]
Oh, definitely. And if we could get something similar to `parallelSlotNames` for the second dimension as well ... I could probably halve my code base for some of my packages.

**Comment by mtmorgan** [comment]
@LTLA if the pull request has settled down I'll merge it into SummarizedExperiment...

**Comment by LTLA** [comment]
Thanks @mtmorgan. Happy for it to go in, and happy for you to make edits at your discretion - I'm definitely not the authoritative source for defining S4 classes. Also looking forward to the refactoring from @hpages; I'm always happy to chip in with thoughts about how to make my life easier.

**Comment by mtmorgan** [comment]
Probably the discussion about `parallelSlotNames` etc should be a different issue.

Thanks Aaron for putting the vignette together!

**Comment by hpages** [comment]
Yes, thanks Aaron. I will try and give a shot at refactoring a few internal things in SummarizedExperiment during this new devel cycle. Out of curiosity, did you come across SummarizedExperiment extensions that add slots parallel to the 2nd dimension? Thanks!

**Pull request merged**
